# Generated by Django 4.2.7 on 2025-10-28 16:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Clave UUID única', unique=True)),
                ('name', models.CharField(help_text='Nombre del organismo autorizado', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Descripción del uso de la clave', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Estado de la clave de acceso')),
                ('is_admin', models.BooleanField(default=False, help_text='Permisos de administrador')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Clave de API',
                'verbose_name_plural': 'Claves de API',
                'ordering': ['-created_at'],
            },
        ),
    ]
