# Generated by Django 4.2.7 on 2025-10-31 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='entidad',
            field=models.CharField(default='SENAPRED', help_text='Nombre oficial del organismo autorizado', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(help_text='Nombre identificatorio técnico', max_length=100),
        ),
    ]
