# Generated by Django 4.2.7 on 2025-10-27 14:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_apikey_is_admin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apikey',
            options={'ordering': ['-created_at'], 'verbose_name': 'Clave de API', 'verbose_name_plural': 'Claves de API'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Notificación de Emergencia', 'verbose_name_plural': 'Notificaciones de Emergencia'},
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='description',
            field=models.TextField(blank=True, help_text='Descripción del uso de la clave', null=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Estado de la clave de acceso'),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Clave UUID única', unique=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='name',
            field=models.CharField(help_text='Nombre del organismo autorizado', max_length=100),
        ),
        migrations.AlterField(
            model_name='notification',
            name='body',
            field=models.TextField(help_text='Descripción detallada de la emergencia'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp del evento'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(blank=True, help_text='Organismo que generó la alerta', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(help_text='Título descriptivo del evento', max_length=255),
        ),
        migrations.AlterField(
            model_name='notification',
            name='topic',
            field=models.CharField(default='general', help_text='Categoría de la notificación', max_length=100),
        ),
    ]
