# Generated by Django 4.2.7 on 2025-10-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_alter_apikey_options_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApiKey',
        ),
        migrations.AddField(
            model_name='notification',
            name='active',
            field=models.BooleanField(default=True, help_text='Estado activo de la emergencia'),
        ),
        migrations.AddField(
            model_name='notification',
            name='emergency_type',
            field=models.CharField(default='general', help_text='Tipo de emergencia', max_length=50),
        ),
        migrations.AddField(
            model_name='notification',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitud del evento', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitud del evento', null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='magnitude',
            field=models.FloatField(blank=True, help_text='Magnitud (para terremotos)', null=True),
        ),
    ]
