# Generated by Django 4.2.7 on 2025-10-31 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_service', '0002_apikey_entidad_alter_apikey_name'),
        ('server', '0005_delete_apikey_notification_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='api_key',
            field=models.ForeignKey(blank=True, help_text='API Key que creó la alerta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth_service.apikey'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='source',
            field=models.CharField(blank=True, help_text='Organismo que generó la alerta', max_length=150, null=True),
        ),
    ]
