# Generated by Django 4.2.7 on 2025-10-31 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='role',
            field=models.CharField(choices=[('user', 'Usuario'), ('admin', 'Administrador')], default='user', max_length=10),
        ),
    ]
